import type { ProjectSummary, DashboardMetrics, Alert, MyProfile } from './types';

export const mockProfile: MyProfile = {
  user_id: '00000000-0000-0000-0000-000000000001',
  email: 'botelladesdeel98@gmail.com',
  full_name: 'Damián Martínez',
  role: 'architect',
  tenant_id: 'bbf3f07e-206c-4a4a-affe-592ae3d6c4c9',
  tenant_name: 'Estudio Damián Martínez',
};

export const mockProjects: ProjectSummary[] = [
  {
    id: 'p1',
    name: 'Reforma Vallecas',
    client_name: 'Lucía González',
    current_phase: 'intake',
    status: 'active',
    budget_target: 45000,
    location_city: 'Madrid',
    created_at: '2026-04-30T10:00:00Z',
    updated_at: '2026-05-01T15:42:00Z',
    tenant_id: mockProfile.tenant_id,
    alerts_count: 1,
    pending_approvals_count: 1,
  },
  {
    id: 'p2',
    name: 'Lavapiés piso',
    client_name: 'Marc Bertran',
    current_phase: 'briefing_done',
    status: 'active',
    budget_target: 72000,
    location_city: 'Madrid',
    created_at: '2026-04-22T09:30:00Z',
    updated_at: '2026-05-02T11:18:00Z',
    tenant_id: mockProfile.tenant_id,
    alerts_count: 0,
    pending_approvals_count: 1,
  },
  {
    id: 'p3',
    name: 'Bajo Embajadores',
    client_name: 'Inés Rey',
    current_phase: 'analysis_done',
    status: 'active',
    budget_target: 48000,
    location_city: 'Madrid',
    created_at: '2026-04-10T14:00:00Z',
    updated_at: '2026-04-28T17:05:00Z',
    tenant_id: mockProfile.tenant_id,
    alerts_count: 2,
    pending_approvals_count: 0,
  },
  {
    id: 'p4',
    name: 'Casa Aravaca',
    client_name: 'Pablo Alfonso',
    current_phase: 'costs_done',
    status: 'active',
    budget_target: 138000,
    location_city: 'Madrid',
    created_at: '2026-03-15T08:45:00Z',
    updated_at: '2026-04-29T19:30:00Z',
    tenant_id: mockProfile.tenant_id,
    alerts_count: 0,
    pending_approvals_count: 1,
  },
  {
    id: 'p5',
    name: 'Ático Chamberí',
    client_name: 'Beatriz Soler',
    current_phase: 'trades_done',
    status: 'active',
    budget_target: 92000,
    location_city: 'Madrid',
    created_at: '2026-02-20T11:00:00Z',
    updated_at: '2026-04-25T16:00:00Z',
    tenant_id: mockProfile.tenant_id,
    alerts_count: 1,
    pending_approvals_count: 0,
  },
];

export const mockMetrics: DashboardMetrics = {
  active_projects: mockProjects.filter((p) => p.status === 'active').length,
  projects_by_phase: mockProjects.reduce<Record<string, number>>((acc, p) => {
    acc[p.current_phase] = (acc[p.current_phase] || 0) + 1;
    return acc;
  }, {}),
  critical_alerts: mockProjects.reduce((acc, p) => acc + (p.alerts_count > 1 ? 1 : 0), 0),
  pending_approvals: mockProjects.reduce((acc, p) => acc + p.pending_approvals_count, 0),
  revenue_pipeline_eur: mockProjects.reduce((acc, p) => acc + (p.budget_target || 0), 0),
  llm_cost_mtd_usd: 12.34,
};

export const mockAlerts: Alert[] = [
  {
    id: 'a1',
    project_id: 'p1',
    type: 'approval_pending',
    severity: 'warning',
    title: 'Aprobación pendiente: briefing_review',
    message: 'Briefing v1 generado, espera revisión',
    created_at: '2026-05-01T15:42:00Z',
    resolved_at: null,
  },
  {
    id: 'a2',
    project_id: 'p3',
    type: 'regulatory_warning',
    severity: 'critical',
    title: 'CTE DB-HE: aislamiento térmico fachada norte',
    message: 'Cumplimiento dudoso, requiere certificado energético previo',
    created_at: '2026-04-28T17:05:00Z',
    resolved_at: null,
  },
  {
    id: 'a3',
    project_id: 'p3',
    type: 'consultation',
    severity: 'warning',
    title: 'Consulta de agent_design',
    message: 'Conflicto entre cocina abierta y normativa acústica DB-HR',
    created_at: '2026-04-27T10:18:00Z',
    resolved_at: null,
  },
  {
    id: 'a4',
    project_id: 'p2',
    type: 'approval_pending',
    severity: 'warning',
    title: 'Aprobación pendiente: design_review',
    message: '3 opciones de diseño esperando selección del arquitecto',
    created_at: '2026-05-02T11:18:00Z',
    resolved_at: null,
  },
  {
    id: 'a5',
    project_id: 'p5',
    type: 'agent_failure',
    severity: 'critical',
    title: 'Fallo en agent_proposal',
    message: 'Timeout esperando respuesta LLM',
    created_at: '2026-04-25T16:00:00Z',
    resolved_at: null,
  },
];
