-- 078: Fase E.2 - SEED Barcelona (PGM 1976 + Eixample + Ciutat Vella + normativa CAT)
-- 19 reglas. Vocabulario PGOU (no BD enum).

BEGIN;

INSERT INTO municipal_pgou_rules (municipio_slug, municipio_nombre, provincia, ccaa, rule_key, rule_category, rule_title, rule_description, normative_reference, normative_url, applies_to, triggers, license_implication, pitfalls, severity, source_doc) VALUES

('barcelona','Barcelona','Barcelona','Cataluña','reforma_interior_comunicat_obres','tramite_licencia',
 'Reforma interior sin afectar estructura: comunicat d obres',
 'Reformas que no tocan elementos estructurales ni fachada, sustitucion de revestimientos, sanitarios, ventanas sin modificar hueco: comunicat d obres (24h-15 dies segun complejidad). Memoria + fotos suficientes en muchos casos.',
 'OMAU (Ordenanza Reguladora Procediment Comunicat) Barcelona',
 'https://ajuntament.barcelona.cat/ca/informacio-administrativa/permisos-i-llicencies',
 '{"project_type":["reforma","actuacion_simple"]}'::jsonb,
 '{"affects_structure":false,"changes_layout":false}'::jsonb,
 'comunicacion_previa',
 '["BCN distingue Comunicat I (simple) y Comunicat II (mas exigente). Comunicat I admite inicio inmediato; Comunicat II requiere espera 15 dias.","Si tocas instalaciones comunes (bajantes verticales) pasa a Comunicat II o Llicencia."]'::jsonb,
 'critico','OMAU Barcelona'),

('barcelona','Barcelona','Barcelona','Cataluña','reforma_distribucio_llicencia','tramite_licencia',
 'Reforma con cambio de distribucion: llicencia d obres menors',
 'Modificar tabiqueria interior sin afectar elementos estructurales: llicencia d obres menors. Requiere proyecto tecnico firmado por arquitecto o aparejador. Plazo resolucion 1-2 meses.',
 'OMAU + Decret Legislatiu 1/2010 TRLU Catalunya',
 'https://portaljuridic.gencat.cat',
 '{"project_type":["reforma"]}'::jsonb,
 '{"changes_layout":true,"affects_structure":false}'::jsonb,
 'declaracion_responsable',
 '["A Barcelona obres menors siempre llicencia (no DR como en Madrid). Mas exigente.","Si afecta elemento comun (patio, fachada) acta junta comunidad obligatoria antes."]'::jsonb,
 'critico','TRLU Catalunya'),

('barcelona','Barcelona','Barcelona','Cataluña','obra_estructural_majors','tramite_licencia',
 'Reforma que afecta estructura o cambio uso: llicencia obres majors',
 'Tocar elementos estructurales, modificar fachada, cambio de uso, division horizontal, ampliacion: llicencia obres majors. Proyecto basico + ejecucio visado COAC. Plazo 3-6 meses.',
 'TRLU Catalunya art. 187 + OMAU',
 'https://portaljuridic.gencat.cat',
 '{"project_type":["reforma","cambio_uso","division_horizontal","obra_nueva","ampliacion"]}'::jsonb,
 '{"affects_structure":true}'::jsonb,
 'licencia_obra_mayor',
 '["Caducidad llicencia 6 mesos sense iniciar / 12 mesos sense acabar fase. Renovacio cara.","Pagament ICIO 4% pressupost + taxa = ~4.5% del PEM."]'::jsonb,
 'critico','TRLU + OMAU'),

('barcelona','Barcelona','Barcelona','Cataluña','ciutat_vella_eixample_patrimoni','proteccion_patrimonio',
 'Ciutat Vella + Eixample: Pla Especial + Patrimoni catalogat',
 'Inmuebles en Ciutat Vella (BIC), Eixample Cerda (catalogat conjunt), Gracia, Sant Andreu, etc. con catalogacion BCIN/BIC requieren informe favorable Patrimoni + posibles restricciones materiales. Ventanas, baranas, miradores: matricula identica obligatoria.',
 'Pla Especial Proteccio Patrimoni + Llei 9/1993 Patrimoni Catalunya',
 'https://patrimoni.gencat.cat',
 '{"property_type":["any"]}'::jsonb,
 '{"location_zone":["ciutat_vella","eixample","gracia","sant_andreu","catalogat"],"affects_facade":true}'::jsonb,
 'licencia_obra_mayor',
 '["L Eixample sencer es conjunt protegit - cualquier intervencion en fachada va a Patrimoni Generalitat (+2 mesos).","Galeries Eixample: no se puede cerrar sin proyecto especifico aprobado."]'::jsonb,
 'critico','Pla Patrimoni BCN'),

('barcelona','Barcelona','Barcelona','Cataluña','ascensor_obligatori_decret_28','ascensor_obligatorio',
 'Decret 28/2010 accessibilitat: ascensor obligatorio rehabilitacion >25%',
 'Edificios de mas de PB+3 plantas sobre rasante: ascensor obligatorio en obra nueva. En rehabilitacion >25% valor edifici: instalar ascensor o justificar impossibilitat tecnica/economica. Cabin minima 90x120 cm + porta 80 cm.',
 'Decret 28/2010 + Codi Accessibilitat Catalunya',
 'https://portaljuridic.gencat.cat',
 '{"project_type":["obra_nueva","rehabilitacion","cambio_uso"]}'::jsonb,
 '{"property_floors_above_ground":">=4","reform_pct_value":">=25"}'::jsonb,
 'depende',
 '["A Catalunya el llindar es PB+3 (4 plantes), no PB+4 como Madrid. Mas restrictivo.","Subvencio Generalitat fins 60% cost si comunitat veins acorda en junta."]'::jsonb,
 'critico','Decret 28/2010'),

('barcelona','Barcelona','Barcelona','Cataluña','habitabilitat_decret_141_2012','habitabilidad_minima',
 'Decret 141/2012 condicions habitabilitat: minimo 36 m2 1 dormitori',
 'Habitabilitat habitatges nous a Catalunya: estudi minim 36 m2 utils (mas restrictivo que CAM). Cada dormitori >=8 m2 (>=6 m2 si auxiliar). Bany amb dutxa+lavabo+wc. Cuina podra ser independent o integrada.',
 'Decret 141/2012 Habitabilitat Catalunya',
 'https://portaljuridic.gencat.cat',
 '{"project_type":["obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"creates_dwelling":true}'::jsonb,
 'depende',
 '["Catalunya exigeix 36 m2 estudi (vs 25 m2 Madrid). Important comprovar abans de divisio.","En existents pre-1984 amb cedula d habitabilitat vigent es respecta el regim anterior."]'::jsonb,
 'critico','Decret 141/2012'),

('barcelona','Barcelona','Barcelona','Cataluña','cedula_habitabilitat_catalunya','habitabilidad_minima',
 'Cedula d habitabilitat: obligatoria per transmissio i suministrament',
 'Cedula d habitabilitat obligatoria per llogar, vendre o donar d alta llum/aigua/gas a Catalunya. Caducidad 15 anys (1a ocupacio) o 25 anys (2a ocupacio). Cedula caducada bloqueja contracte.',
 'Decret 141/2012 + Decret 67/2015 Habitabilitat',
 'https://habitatge.gencat.cat',
 '{"project_type":["any"]}'::jsonb,
 '{"is_residential":true}'::jsonb,
 'sin_licencia',
 '["Renovacio cedula tras reforma exigida abans d alta suministraments. Plazo 1-2 setmanes.","Sense cedula vigent no hi ha alta llum ni gas - obra parada esperant tramit."]'::jsonb,
 'critico','Decret 141/2012'),

('barcelona','Barcelona','Barcelona','Cataluña','dbhe_cte_envolvent_25pct','eficiencia_energetica',
 'CTE DB-HE reforma >25% envolvent + Decret 21/2006 eco-eficiencia',
 'Reforma >25% envolvent termica: cumplir DB-HE0/HE1. Catalunya afegeix Decret 21/2006 eco-eficiencia: aigua calenta sanitaria amb solar termica (o equivalent) en rehabilitacio integral. Carpinteria U <= 1.8 W/m2K.',
 'CTE DB-HE + Decret 21/2006 Catalunya',
 'https://portaljuridic.gencat.cat',
 '{"project_type":["reforma","cambio_uso","obra_nueva"]}'::jsonb,
 '{"reform_pct_envelope":">=25"}'::jsonb,
 'depende',
 '["Catalunya exigeix ACS solar (o aerotermia equivalent) en reforma integral - mas que CTE basic.","Documentacio energetica visada COAC en obra major."]'::jsonb,
 'critico','Decret 21/2006'),

('barcelona','Barcelona','Barcelona','Cataluña','ite_catalunya_45anys','ite_iee',
 'ITE Catalunya: obligatoria edificis >45 anys + cada 10 anys',
 'Inspeccio Tecnica Edifici (ITE) obligatoria a Catalunya per edificis amb >45 anys (mas restrictiu que Madrid 30 anys). Cada 10 anys renovacio. Sense ITE vigent no es dona llicencia per reforma >25%.',
 'Decret 67/2015 ITE Catalunya',
 'https://portaljuridic.gencat.cat',
 '{"project_type":["reforma","cambio_uso","division_horizontal"]}'::jsonb,
 '{"building_age_years":">=45"}'::jsonb,
 'depende',
 '["ITE Catalunya conte modul accessibilitat + eficiencia energetica - mas amplia que ITE Madrid.","Cost ITE ~600-1200 EUR segons mida. Comunitat o propietari l ha de pagar."]'::jsonb,
 'critico','Decret 67/2015'),

('barcelona','Barcelona','Barcelona','Cataluña','pati_minim_4x4_metres','patios_ventilacion',
 'Pati interior minim: 4x4 m (16 m2) per ventilacio dormitoris',
 'PGM 1976: pati de ventilacio minim 4x4 m (16 m2) si rep ventilacio de peces vivenda. Pati mes petit nomes per cuines/banys (3x3 m). Galeries d Eixample reglat especific.',
 'PGM 1976 + Ordenances Metropolitanes Edificacio',
 'https://ajuntament.barcelona.cat',
 '{"project_type":["obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"requires_patio":true}'::jsonb,
 'depende',
 '["BCN: pati 16 m2 (vs 9 m2 Madrid). Mas exigent. Important en canvi d us local->habitatge.","Galeria Eixample no es pot tancar sense canvi normatiu - solo manteniment."]'::jsonb,
 'critico','PGM 1976'),

('barcelona','Barcelona','Barcelona','Cataluña','aparcament_pgm_residencial','aparcamiento_obligatorio',
 'Aparcament obligatori: 1 plaza per habitatge fins 100 m2, 2 plaza >100 m2',
 'Obra nueva o ampliacio significativa: 1 plaza aparcament per habitatge fins 100 m2; 2 plazas si supera 100 m2. Centro BCN (Ciutat Vella, part Eixample) atenuacio o exoneracio en catalogats.',
 'PGM 1976 art. 320 + Ordenanca Edificacio',
 'https://ajuntament.barcelona.cat',
 '{"project_type":["obra_nueva","ampliacion"]}'::jsonb,
 '{"is_residential":true,"property_area_m2":">=50"}'::jsonb,
 'depende',
 '["Centro historic exoneracio frequent. Verifica Pla Especial de cada districte.","Divisio horitzontal en existent: normalment NO afegeix obligacio."]'::jsonb,
 'importante','PGM 1976'),

('barcelona','Barcelona','Barcelona','Cataluña','horario_obres_bcn','horario_obras',
 'Horari obres Barcelona: L-V 8:00-20:00, S 9:00-14:00, D festius prohibit',
 'Obres ruidoses zona urbana nomes L-V 8:00-20:00 i S 9:00-14:00. Diumenges i festius prohibit (excepcio: urgencies amb autoritzacio). Maquinaria forta (martell pneumatic) nomes 9:00-19:00.',
 'Ordenança Contaminacio Acustica Barcelona',
 'https://ajuntament.barcelona.cat',
 '{"project_type":["any"]}'::jsonb,
 '{"any":true}'::jsonb,
 'sin_licencia',
 '["BCN multa fins 1500 EUR per incompliment horari. Veins denuncien rapidament.","Per obra urgent fora d horari demanar autoritzacio Districte 48h abans."]'::jsonb,
 'importante','Ordenança BCN'),

('barcelona','Barcelona','Barcelona','Cataluña','rcd_decret_89_2010','gestion_rcd',
 'RCD: Decret 89/2010 Catalunya + fianza municipal',
 'Residus Construccio i Demolicio: separacio i entrega gestor autoritzat amb numero registre. Fiança municipal segons volum estimat (~11 EUR/tona). Llibre incidencies ambientals obligatori.',
 'Decret 89/2010 RCD Catalunya + Decret 21/2006',
 'https://portaljuridic.gencat.cat',
 '{"project_type":["reforma","obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"generates_rcd":true,"estimated_rcd_m3":">=5"}'::jsonb,
 'sin_licencia',
 '["Sense certificat gestor RCD no devolucio fiança. Coordinacio contractista clau.","Punts verds municipals admeten petits volums (<1m3) sense gestor."]'::jsonb,
 'importante','Decret 89/2010'),

('barcelona','Barcelona','Barcelona','Cataluña','andami_via_publica_bcn','tasas_andamios_vados',
 'Andami via publica: autoritzacio Mobilitat + taxa diaria',
 'Andami, contenidor o vado a vorera/calçada: autoritzacio Mobilitat Barcelona. Taxa ~0.5-0.9 EUR/m2/dia. Andamis >6m: certificat tecnic + assegurança RC obligatoria.',
 'Ordenança Mobiliari Urba + Ordenança Taxes BCN',
 'https://ajuntament.barcelona.cat',
 '{"project_type":["reforma","obra_nueva"]}'::jsonb,
 '{"requires_public_space":true}'::jsonb,
 'sin_licencia',
 '["BCN taxes mes altes que Madrid (~50%). Inclou-ho al pressupost obra.","Carrils bici afectats: senyalitzacio especifica obligatoria + protecció ciclistes."]'::jsonb,
 'recomendable','Ordenança BCN'),

('barcelona','Barcelona','Barcelona','Cataluña','comptador_aigua_individual_bcn','instalaciones_servicios',
 'Comptador individual aigua: obligatori Aigues de Barcelona',
 'Reformes integrals o divisio horitzontal: comptador individual per habitatge a registre Aigues de Barcelona (AGBAR). Sense comptador no hi ha alta servei. Acometida ajustada cabal/potencia.',
 'Reglament Subministrament AGBAR + Decret 21/2006',
 'https://www.aigues.barcelona',
 '{"project_type":["reforma","division_horizontal","obra_nueva"]}'::jsonb,
 '{"is_residential":true,"reform_pct_value":">=25"}'::jsonb,
 'sin_licencia',
 '["Coordinacio AGBAR abans inici obra. Tramit 4-8 setmanes per nova acometida.","Subvencio Generalitat per individualitzar comptadors antics."]'::jsonb,
 'importante','AGBAR'),

('barcelona','Barcelona','Barcelona','Cataluña','calefaccio_renovable_bcn_pla_clima','eficiencia_energetica',
 'Pla Clima 2030 BCN: prohibit gasoil/carbó + obligacio renovables',
 'A obres reforma >25% i obra nova: prohibit instalar caldera gasoil o carbó. Obligatori aerotermia, biomassa pellet, geotermia o gas natural condensacio amb solar termica. Pla Clima 2030 BCN preveu prohibicio total gas natural en obra nova residencial 2030.',
 'Pla Clima BCN + Decret 30/2015 ETE + RD 178/2021',
 'https://www.barcelona.cat/barcelona-pel-clima',
 '{"project_type":["reforma","cambio_uso","obra_nueva"]}'::jsonb,
 '{"replaces_heating":true}'::jsonb,
 'sin_licencia',
 '["Subvencions Generalitat fins 40% cost aerotermia.","En obra nova post-2030 valorar ja sense gas natural - inversio durable."]'::jsonb,
 'importante','Pla Clima BCN'),

('barcelona','Barcelona','Barcelona','Cataluña','amiant_pre1984_bcn','otros',
 'Amiant: edificis pre-1984 amb fibrocement requereixen Plan Treball RERA',
 'Reformes amb demolicio en edificis pre-1984 (sospita amiant fibrocement): avaluacio previa obligatoria. Si confirmat: empresa RERA Catalunya autoritzada + Plan Treball aprovat per ICAEN (Inspeccio Treball Catalunya). Sense Pla no es comença demolicio.',
 'RD 396/2006 + Decret 374/1996 Catalunya',
 'https://treball.gencat.cat',
 '{"project_type":["reforma","obra_nueva"]}'::jsonb,
 '{"building_age_years":">=42","demolition_works":true}'::jsonb,
 'sin_licencia',
 '["Baixants uralita pre-1984 = amiant al 95%. Cost retirada 35-65 EUR/ml RERA.","Plan Treball ICAEN: tramit 3-4 setmanes. Planifica abans inici obra."]'::jsonb,
 'critico','Decret 374/1996'),

('barcelona','Barcelona','Barcelona','Cataluña','alcada_lliure_minima_25_residencial','habitabilidad_minima',
 'Alçada lliure minima: 2.50 m peces habitables, 2.40 m banys/cuines',
 'Decret 141/2012 Catalunya: alçada lliure minima 2.50 m peces habitables (estar, dormitoris, cuina principal). 2.40 m en banys, cuines petites, distribuidors. Descens local: 25% de superficie maxim.',
 'Decret 141/2012 Habitabilitat Catalunya',
 'https://portaljuridic.gencat.cat',
 '{"project_type":["obra_nueva","cambio_uso","reforma"]}'::jsonb,
 '{"affects_ceiling_height":true}'::jsonb,
 'depende',
 '["2.40 m a banys (vs 2.20 m Madrid). Important en canvi d us local.","Sostre tecnic baixant alçada: comprovar abans col-locar luminaria empotrada."]'::jsonb,
 'importante','Decret 141/2012'),

('barcelona','Barcelona','Barcelona','Cataluña','canvi_us_compatibilitat_pgm','compatibilidad_uso',
 'Canvi d us terciari->residencial: compatibilitat PGM + Decret 141/2012',
 'Convertir local/oficina en habitatge a BCN: (1) compatibilitat us residencial a la qualificacio PGM (no a totes les zones), (2) compliment Decret 141/2012 (36 m2 minim, alcada 2.50 m, ventilacio natural a carrer/pati 16 m2), (3) ITE vigent, (4) Pla d Usos de Districte (limit densitat turistica/residencial).',
 'PGM 1976 + Decret 141/2012 + Pla Usos Districtes',
 'https://ajuntament.barcelona.cat',
 '{"project_type":["cambio_uso"]}'::jsonb,
 '{"new_use":"residencial","origin_use":["terciario","comercial","oficina"]}'::jsonb,
 'licencia_obra_mayor',
 '["Plans d Usos districtes (Ciutat Vella, Eixample, Gracia, Sant Marti) limiten conversions terciari->residencial.","Local planta baixa a Eixample: comprovar Pla d Usos i compatibilitat amb activitat veina."]'::jsonb,
 'critico','Pla d Usos BCN')

ON CONFLICT (municipio_slug, rule_key) DO UPDATE SET
  rule_description = EXCLUDED.rule_description,
  normative_reference = EXCLUDED.normative_reference,
  normative_url = EXCLUDED.normative_url,
  applies_to = EXCLUDED.applies_to,
  triggers = EXCLUDED.triggers,
  license_implication = EXCLUDED.license_implication,
  pitfalls = EXCLUDED.pitfalls,
  severity = EXCLUDED.severity,
  version_rule = municipal_pgou_rules.version_rule + 1,
  last_verified_at = now(),
  updated_at = now();

INSERT INTO applied_migrations (filename, notes) VALUES
  ('078_municipal_pgou_barcelona.sql', 'E.2 plan Opus: seed Barcelona (19 reglas PGM 1976 + Eixample + Ciutat Vella + normativa Catalunya)')
ON CONFLICT (filename) DO NOTHING;

COMMIT;

-- rollback: DELETE FROM municipal_pgou_rules WHERE municipio_slug = 'barcelona'; DELETE FROM applied_migrations WHERE filename = '078_municipal_pgou_barcelona.sql';
