-- 079: Fase E.2 - SEED Valencia (PGOU 1988 rev 2014 + LOTUP + ZIP Ciutat Vella + riesgo inundacion)
-- 18 reglas.

BEGIN;

INSERT INTO municipal_pgou_rules (municipio_slug, municipio_nombre, provincia, ccaa, rule_key, rule_category, rule_title, rule_description, normative_reference, normative_url, applies_to, triggers, license_implication, pitfalls, severity, source_doc) VALUES

('valencia','Valencia','Valencia','Comunitat Valenciana','obras_menores_dr_valencia','tramite_licencia',
 'Obras menores Valencia: declaracion responsable mas amplia que CAM',
 'Reformas interiores sin afectar estructura ni fachada (pintura, pavimentos, banos, cocinas, ventanas sin modificar hueco, distribucion tabiqueria no portante): DR. Memoria firmada + foto + plano sencillo. Inicio inmediato.',
 'Ley 5/2014 LOTUP art. 213 + Ordenanza Municipal Valencia',
 'https://www.valencia.es/cas/urbanismo/licencias',
 '{"project_type":["reforma","actuacion_simple"]}'::jsonb,
 '{"affects_structure":false,"changes_layout":true}'::jsonb,
 'declaracion_responsable',
 '["Valencia mas permisiva en DR: hasta cambio distribucion sin estructura entra como DR (Madrid lo trata aparte).","Revision a posteriori - mantener documentacion 6 anys per si revisio."]'::jsonb,
 'critico','LOTUP 5/2014'),

('valencia','Valencia','Valencia','Comunitat Valenciana','obra_estructural_licencia_mayor_val','tramite_licencia',
 'Obra mayor Valencia: cambio estructura, uso, division horizontal',
 'Afectar elementos estructurales (pilares, vigas, forjados), modificar fachada, cambio de uso, division horizontal o ampliacion: licencia urbanistica. Proyecto basico + ejecucion visado CTAV. Plazo 2-4 mesos.',
 'LOTUP art. 214 + PGOU Valencia 1988 rev 2014',
 'https://www.valencia.es',
 '{"project_type":["reforma","cambio_uso","division_horizontal","obra_nueva","ampliacion"]}'::jsonb,
 '{"affects_structure":true}'::jsonb,
 'licencia_obra_mayor',
 '["ICIO Valencia 3.3% PEM + tasa 0.9% = ~4.2% total. Mas baix que BCN.","Visat CTAV obligatori per obra mayor."]'::jsonb,
 'critico','LOTUP + PGOU'),

('valencia','Valencia','Valencia','Comunitat Valenciana','ciutat_vella_zip_patrimoni','proteccion_patrimonio',
 'Ciutat Vella Valencia (ZIP) + La Lonja BIC + El Carmen',
 'Ciutat Vella esta declarada Zona Interior Protegida (ZIP). La Lonja Patrimonio UNESCO. Casco antiguo (El Carmen, Velluters, Seu-Xerea, Mercat) requiere informe favorable Conselleria Cultura. Materiales tradicionales obligatorios: madera, hierro forjado, teja arabe.',
 'Plan Especial Ciutat Vella + Ley 4/1998 Patrimonio CV',
 'https://www.valencia.es/cas/urbanismo/planeamiento',
 '{"property_type":["any"]}'::jsonb,
 '{"location_zone":["ciutat_vella","el_carmen","velluters","seu_xerea","mercat","zip"],"affects_facade":true}'::jsonb,
 'licencia_obra_mayor',
 '["En ZIP cualquier intervencion fachada requiere informe Conselleria Cultura (+1-2 mesos).","PVC y aluminio en ventanas prohibidos en muchos catalogados - solo madera o hierro."]'::jsonb,
 'critico','Plan Especial Ciutat Vella'),

('valencia','Valencia','Valencia','Comunitat Valenciana','riesgo_inundacion_turia_cota_minima','otros',
 'Riesgo inundacion: cota minima planta baja en zonas Turia/Albufera',
 'Zonas con riesgo de inundacion (definidas en mapas PATRICOVA + Plan Especial Turia): planta baja a cota minima sobre rasante (>= 0.5 m). Camaras bufa obligatorias. Materiales hidrofugos en bajos. Sin riesgo declarado no aplica.',
 'PATRICOVA + Plan Especial Turia + RD 903/2010 Inundaciones',
 'https://politicaterritorial.gva.es/patricova',
 '{"project_type":["obra_nueva","cambio_uso","reforma"]}'::jsonb,
 '{"flood_risk_zone":true,"affects_ground_floor":true}'::jsonb,
 'depende',
 '["Comprobar mapa PATRICOVA antes de proyectar planta baja - exclusivo Valencia.","Cambio uso local->vivienda planta baja en zona PATRICOVA puede ser inviable."]'::jsonb,
 'critico','PATRICOVA'),

('valencia','Valencia','Valencia','Comunitat Valenciana','ascensor_obligatorio_valencia','ascensor_obligatorio',
 'Ascensor obligatorio: edificios >4 plantas + Ley 1/1998 accesibilidad CV',
 'Obra nueva PB+3 (4 plantas): ascensor obligatorio. Rehabilitacion >25% en edificio >=4 plantas: instalar ascensor o justificar inviabilidad. Cabina minima 1.10 m x 1.40 m + puerta 80 cm.',
 'Ley 1/1998 Accesibilidad CV + CTE DB-SUA',
 'https://www.boe.es/eli/es-vc/l/1998/05/05/1',
 '{"project_type":["obra_nueva","rehabilitacion","cambio_uso"]}'::jsonb,
 '{"property_floors_above_ground":">=4","reform_pct_value":">=25"}'::jsonb,
 'depende',
 '["Ley CV 1/1998 mas exigente en dimensiones cabina que CTE basico.","Subvencion IVACE + Generalitat hasta 60% si comunidad aprueba en junta."]'::jsonb,
 'critico','Ley 1/1998 CV'),

('valencia','Valencia','Valencia','Comunitat Valenciana','habitabilidad_decreto_65_2007','habitabilidad_minima',
 'Decreto 65/2007 CV: condiciones habitabilidad - 30 m2 estudio',
 'Habitabilidad Comunitat Valenciana: estudio minimo 30 m2 utils (entre Madrid 25 m2 y BCN 36 m2). Cada dormitorio adicional >= 8 m2. Bano: ducha o banera + lavabo + wc. Cocina puede ser integrada en estancia >18 m2.',
 'Decreto 65/2007 CV Condiciones Habitabilidad',
 'https://dogv.gva.es',
 '{"project_type":["obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"creates_dwelling":true}'::jsonb,
 'depende',
 '["CV 30 m2 estudio (Madrid 25, BCN 36). Posicion intermedia.","Cocina integrada permitida >18 m2 sala - aprovechar para optimizar espacio."]'::jsonb,
 'critico','Decreto 65/2007 CV'),

('valencia','Valencia','Valencia','Comunitat Valenciana','dbhe_cte_valencia','eficiencia_energetica',
 'CTE DB-HE Valencia + clima mediterraneo - refrigeracion exigente',
 'Reforma >25% envolvente: DB-HE0/HE1. Valencia clima mediterraneo (zona B3) exige mayor proteccion solar verano. Carpinterias U <= 1.8 W/m2K + factor solar g <= 0.4 en orientacion S/O. Inversion proteccion solar (toldos, lamas, persianas) recuperable rapido.',
 'CTE DB-HE (RD 732/2019 zona B3)',
 'https://www.codigotecnico.org',
 '{"project_type":["reforma","cambio_uso","obra_nueva"]}'::jsonb,
 '{"reform_pct_envelope":">=25"}'::jsonb,
 'depende',
 '["Zona B3 Valencia: factor solar g critic (Mediterraneo calor). No basta U baja - proteccion solar obligatoria.","Aerotermia subvencionada IVACE hasta 40% cost."]'::jsonb,
 'importante','CTE DB-HE'),

('valencia','Valencia','Valencia','Comunitat Valenciana','ite_valencia_50anys','ite_iee',
 'ITE Valencia: edificios >50 anos cada 10 anos (menos exigente que CAT)',
 'ITE Valencia: edificios con mas de 50 anos (vs 30 Madrid, 45 BCN). Cada 10 anos renovacion. Sin ITE vigente, no licencia para reforma >25%. Coste 500-900 EUR.',
 'Ordenanza ITE Valencia + Ley 8/2004 Suelo CV',
 'https://www.valencia.es/cas/urbanismo/ite',
 '{"project_type":["reforma","cambio_uso","division_horizontal"]}'::jsonb,
 '{"building_age_years":">=50"}'::jsonb,
 'depende',
 '["Valencia umbral 50 anos - mas permissivo que Madrid (30) o BCN (45).","En conjuntos historicos (Ciutat Vella) ITE recomendada incluso <50 anos."]'::jsonb,
 'importante','Ordenanza Valencia'),

('valencia','Valencia','Valencia','Comunitat Valenciana','patio_minimo_valencia_3m','patios_ventilacion',
 'Patio ventilacion: minimo 3x3 m (9 m2) zona EDR / 4x4 m (16 m2) Ensanche',
 'PGOU Valencia: patio ventilacion minimo varia segun zona. EDR (Edificacion Densidad Residencial): 9 m2. Ensanche/PGOU especifico: 16 m2 si recibe ventilacion dormitorios. Centro historico tablas especificas.',
 'PGOU Valencia 1988 rev 2014',
 'https://www.valencia.es/cas/urbanismo/planeamiento',
 '{"project_type":["obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"requires_patio":true}'::jsonb,
 'depende',
 '["Comprobar zona PGOU antes - 9 m2 o 16 m2 segun calificacion.","Cambio uso local centro historico: pati exige Plan Especial verificacion."]'::jsonb,
 'importante','PGOU Valencia'),

('valencia','Valencia','Valencia','Comunitat Valenciana','aparcamiento_valencia_1x100','aparcamiento_obligatorio',
 'Aparcamiento: 1 plaza/100 m2 residencial obra nueva',
 'Obra nueva o ampliacion >25% residencial: 1 plaza aparcamiento por 100 m2 construidos. Centro historico (Ciutat Vella) exoneracion frecuente. Edificios protegidos: tabla de exoneracion segun grado.',
 'PGOU Valencia + Ordenanza Municipal',
 'https://www.valencia.es',
 '{"project_type":["obra_nueva","ampliacion"]}'::jsonb,
 '{"is_residential":true,"property_area_m2":">=100"}'::jsonb,
 'depende',
 '["Centro historico Valencia exonera por imposibilidad fisica. Consultar Servicio Licencias.","Plaza minima 2.20 x 4.50 m (similar a Madrid)."]'::jsonb,
 'importante','PGOU Valencia'),

('valencia','Valencia','Valencia','Comunitat Valenciana','horario_obras_valencia','horario_obras',
 'Horario obras Valencia: L-V 8:00-21:00, S 9:00-14:00, D festivos prohibido',
 'Obras zona urbana solo L-V 8:00-21:00 (1h mas que Madrid/BCN al cerrar) y S 9:00-14:00. Domingos prohibido. Maquinaria pesada (martillo, vibrador) solo L-V 9:00-20:00. Periodo Falles (Marzo) restricciones adicionales en zonas afectadas.',
 'Ordenanza Proteccion Acustica Valencia',
 'https://www.valencia.es',
 '{"project_type":["any"]}'::jsonb,
 '{"any":true}'::jsonb,
 'sin_licencia',
 '["Falles (15-19 marzo) zona afectada: obras suspendidas en area Fallas. Plan obra en consecuencia.","Sancion fins 3000 EUR per incompliment reiterat."]'::jsonb,
 'importante','Ordenanza Valencia'),

('valencia','Valencia','Valencia','Comunitat Valenciana','rcd_valencia_decreto_200','gestion_rcd',
 'RCD Valencia: Decreto 200/2004 + fianza segun volumen estimado',
 'Residuos Construccion Demolicion: separacion en origen + entrega gestor autorizado registro CV. Fianza segun PEM (~1-2% PEM). Certificado gestor obligatorio para devolucion. Centros gestion publica disponibles (EMSHI Valencia).',
 'Decreto 200/2004 CV + RD 105/2008',
 'https://medioambiente.gva.es',
 '{"project_type":["reforma","obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"generates_rcd":true,"estimated_rcd_m3":">=5"}'::jsonb,
 'sin_licencia',
 '["Ecoparcs municipals admeten petits volums sense gestor (<2 m3).","Fiança RCD: pres pres recuperable nomes amb certificat gestor."]'::jsonb,
 'importante','Decreto 200/2004 CV'),

('valencia','Valencia','Valencia','Comunitat Valenciana','andamio_valencia','tasas_andamios_vados',
 'Andamio via publica Valencia: tasa Movilidad + autorizacion',
 'Andamio, contenedor o vado en acera/calzada: autorizacion Servicio Movilidad + tasa diaria ~0.3-0.7 EUR/m2/dia. Solicitud 10-15 dias antes. Andamios >6m con certificado tecnico + seguro RC.',
 'Ordenanza Mobiliario Urbano + Tasas Valencia',
 'https://www.valencia.es',
 '{"project_type":["reforma","obra_nueva"]}'::jsonb,
 '{"requires_public_space":true}'::jsonb,
 'sin_licencia',
 '["Valencia tasas mas bajas que BCN/Madrid. Ventaja pressupuestaria.","Zonas ZAS (Zona Acustica Saturada) restricciones horario."]'::jsonb,
 'recomendable','Ordenanza Valencia'),

('valencia','Valencia','Valencia','Comunitat Valenciana','contador_agua_emivasa','instalaciones_servicios',
 'Contador agua individual: EMIVASA Valencia',
 'Reformas integrales o division horizontal: contador individual EMIVASA (concesionaria agua Valencia). Sin contador no hay alta servicio. Acometida ajustada cabal/potencia. Tramite EMIVASA 3-6 semanas.',
 'Reglamento EMIVASA + Decreto 65/2007 CV',
 'https://www.emivasa.es',
 '{"project_type":["reforma","division_horizontal","obra_nueva"]}'::jsonb,
 '{"is_residential":true,"reform_pct_value":">=25"}'::jsonb,
 'sin_licencia',
 '["EMIVASA gestion mas lenta que AGBAR BCN. Pedir alta con tiempo.","Edificios pre-1990 con contador comun: individualizacion subvencionada por GVA."]'::jsonb,
 'importante','EMIVASA'),

('valencia','Valencia','Valencia','Comunitat Valenciana','renovables_obligatorias_pnec_valencia','eficiencia_energetica',
 'Renovables obligatorias: solar termica ACS + prohibicion gasoil',
 'Reforma integral residencial: sustitucion caldera gasoil prohibida (RD 178/2021). Obligatorio aerotermia, biomasa pellet, gas natural condensacion con apoyo solar termico (RD 314/2006 CTE DB-HE4). Valencia clima ideal para solar termica - amortizacion 4-6 anos.',
 'CTE DB-HE4 + PNIEC 2030 + RD 178/2021',
 'https://www.boe.es/buscar/act.php?id=BOE-A-2021-4682',
 '{"project_type":["reforma","cambio_uso","obra_nueva"]}'::jsonb,
 '{"replaces_heating":true}'::jsonb,
 'sin_licencia',
 '["Valencia clima B3: solar termica ACS muy rentable (4-6 anos amortizacion).","IVACE subvenciones aerotermia + solar termica hasta 35-45% cost."]'::jsonb,
 'importante','RD 178/2021'),

('valencia','Valencia','Valencia','Comunitat Valenciana','amianto_pre1980_valencia','otros',
 'Amianto: edificios pre-1980 evaluacion previa + RERA',
 'Reformas con demolicion en edificios pre-1980 (sospecha amianto fibrocemento): evaluacion previa obligatoria. Si confirmado: empresa RERA Valencia autorizada + Plan de Trabajo aprobado por Inspeccion Trabajo CV. Plazo 3-4 semanas.',
 'RD 396/2006 + Ley 31/1995 PRL',
 'https://www.boe.es/buscar/act.php?id=BOE-A-2006-6474',
 '{"project_type":["reforma","obra_nueva"]}'::jsonb,
 '{"building_age_years":">=45","demolition_works":true}'::jsonb,
 'sin_licencia',
 '["Edificios Eixample Valencia 1950-1970: alto riesgo amianto en bajantes/cubiertas.","Cost retirada 30-60 EUR/ml RERA. Planifica en presupuesto."]'::jsonb,
 'critico','RD 396/2006'),

('valencia','Valencia','Valencia','Comunitat Valenciana','altura_libre_valencia_25','habitabilidad_minima',
 'Altura libre minima Valencia: 2.50 m piezas habitables, 2.20 m banos',
 'Decreto 65/2007 CV: altura libre minima 2.50 m en piezas habitables (estar, dormitorios, cocina). 2.20 m banos, pasillos. Descuelgues hasta 25% superficie.',
 'Decreto 65/2007 CV Habitabilidad',
 'https://dogv.gva.es',
 '{"project_type":["obra_nueva","cambio_uso","reforma"]}'::jsonb,
 '{"affects_ceiling_height":true}'::jsonb,
 'depende',
 '["Valencia 2.20 m banos (igual a Madrid, menos exigente que BCN 2.40 m).","Cambios uso local centro historico fallan frecuentemente por altura libre."]'::jsonb,
 'importante','Decreto 65/2007 CV'),

('valencia','Valencia','Valencia','Comunitat Valenciana','cambio_uso_compatibilidad_valencia','compatibilidad_uso',
 'Cambio uso terciario->residencial: compatibilidad PGOU + Decreto 65/2007',
 'Convertir local/oficina en vivienda Valencia: (1) compatibilidad uso residencial en zona PGOU, (2) cumplir Decreto 65/2007 (30 m2 minimo, 2.50 m altura, ventilacion natural calle/pati), (3) si zona PATRICOVA cota planta baja >=0.5 m, (4) ITE vigente edificio.',
 'PGOU Valencia + Decreto 65/2007 + PATRICOVA',
 'https://www.valencia.es',
 '{"project_type":["cambio_uso"]}'::jsonb,
 '{"new_use":"residencial","origin_use":["terciario","comercial","oficina"]}'::jsonb,
 'licencia_obra_mayor',
 '["Plan Especial Ciutat Vella limita conversion terciario->residencial en algunas calles (proteccion uso comercial historico).","PATRICOVA puede invalidar conversion en plantas bajas zona inundable."]'::jsonb,
 'critico','PGOU + PATRICOVA')

ON CONFLICT (municipio_slug, rule_key) DO UPDATE SET
  rule_description = EXCLUDED.rule_description,
  normative_reference = EXCLUDED.normative_reference,
  normative_url = EXCLUDED.normative_url,
  applies_to = EXCLUDED.applies_to,
  triggers = EXCLUDED.triggers,
  license_implication = EXCLUDED.license_implication,
  pitfalls = EXCLUDED.pitfalls,
  severity = EXCLUDED.severity,
  version_rule = municipal_pgou_rules.version_rule + 1,
  last_verified_at = now(),
  updated_at = now();

INSERT INTO applied_migrations (filename, notes) VALUES
  ('079_municipal_pgou_valencia.sql', 'E.2 plan Opus: seed Valencia (18 reglas PGOU 1988 rev 2014 + LOTUP + ZIP Ciutat Vella + PATRICOVA)')
ON CONFLICT (filename) DO NOTHING;

COMMIT;

-- rollback: DELETE FROM municipal_pgou_rules WHERE municipio_slug = 'valencia'; DELETE FROM applied_migrations WHERE filename = '079_municipal_pgou_valencia.sql';
