-- 080: Fase E.2 - SEED Sevilla (PGOU 2006 + LOUA Andalucia + Casco Antiguo BIC + calor extremo)
-- 18 reglas.

BEGIN;

INSERT INTO municipal_pgou_rules (municipio_slug, municipio_nombre, provincia, ccaa, rule_key, rule_category, rule_title, rule_description, normative_reference, normative_url, applies_to, triggers, license_implication, pitfalls, severity, source_doc) VALUES

('sevilla','Sevilla','Sevilla','Andalucia','obras_menores_dr_sevilla','tramite_licencia',
 'Obras menores Sevilla: declaracion responsable LOUA',
 'Reformas interiores sin afectar estructura ni fachada (pintura, pavimentos, sanitarios, ventanas sin modificar hueco, distribucion tabiqueria no portante): DR. Memoria firmada + foto + plano de planta. Inicio inmediato.',
 'Ley 7/2002 LOUA + Ordenanza Sevilla',
 'https://www.sevilla.org/urbanismo',
 '{"project_type":["reforma","actuacion_simple"]}'::jsonb,
 '{"affects_structure":false,"changes_layout":false}'::jsonb,
 'declaracion_responsable',
 '["LOUA Andalucia DR como Valencia. Revision a posteriori - manten documentacion.","DR Casco Antiguo Sevilla: revision mas estricta - incluye informe Patrimonio."]'::jsonb,
 'critico','LOUA 7/2002'),

('sevilla','Sevilla','Sevilla','Andalucia','reforma_distribucion_licencia_sevilla','tramite_licencia',
 'Reforma cambio distribucion (no estructura): licencia obra menor',
 'Modificar tabiqueria interior sin afectar elementos estructurales: licencia obra menor. Proyecto tecnico firmado arquitecto o aparejador, visado CAS (Colegio Aparejadores Sevilla) o COAS (Arquitectos).',
 'LOUA + PGOU Sevilla 2006',
 'https://www.sevilla.org',
 '{"project_type":["reforma"]}'::jsonb,
 '{"changes_layout":true,"affects_structure":false}'::jsonb,
 'licencia_obra_menor',
 '["Plazo resolucion licencia menor 1-2 mesos en Sevilla.","Casco Antiguo: informe Patrimonio aun en obra menor."]'::jsonb,
 'critico','LOUA + PGOU 2006'),

('sevilla','Sevilla','Sevilla','Andalucia','obra_mayor_estructura_sevilla','tramite_licencia',
 'Obra mayor: estructura, cambio uso, division horizontal',
 'Afectar elementos estructurales, modificar fachada, cambio de uso, division horizontal o ampliacion: licencia obra mayor. Proyecto basico + ejecucion visado. Plazo 3-5 mesos en Sevilla.',
 'LOUA art. 169 + PGOU Sevilla 2006',
 'https://www.sevilla.org',
 '{"project_type":["reforma","cambio_uso","division_horizontal","obra_nueva","ampliacion"]}'::jsonb,
 '{"affects_structure":true}'::jsonb,
 'licencia_obra_mayor',
 '["ICIO Sevilla 4% PEM + tasa = ~4.5% total. Similar a Madrid.","Visado CAS o COAS obligatorio en obra mayor."]'::jsonb,
 'critico','LOUA + PGOU 2006'),

('sevilla','Sevilla','Sevilla','Andalucia','casco_antiguo_bic_sevilla','proteccion_patrimonio',
 'Casco Antiguo Sevilla declarado BIC + Conjunto Historico (UNESCO)',
 'Casco Antiguo Sevilla (Santa Cruz, San Salvador, Encarnacion, Macarena, Triana) declarado BIC en 1990 + Conjunto Historico UNESCO. Cualquier intervencion fachada, cubierta o elementos catalogados requiere informe Conserjeria Cultura JA. Materiales tradicionales: cal, tejas arabes, madera, hierro forjado.',
 'Ley 14/2007 PHA + Plan Especial Casco Antiguo Sevilla',
 'https://www.juntadeandalucia.es/organismos/culturaypatrimoniohistorico',
 '{"property_type":["any"]}'::jsonb,
 '{"location_zone":["casco_antiguo","santa_cruz","san_salvador","triana","encarnacion","macarena","bic"],"affects_facade":true}'::jsonb,
 'licencia_obra_mayor',
 '["Casco Antiguo Sevilla mas restrictivo que Madrid Centro - Patrimonio JA implacable con materiales tradicionales.","Aluminio y PVC prohibidos en ventanas catalogadas. Solo madera, hierro forjado tradicional."]'::jsonb,
 'critico','BIC 1990 + Plan Especial'),

('sevilla','Sevilla','Sevilla','Andalucia','ascensor_obligatorio_andalucia','ascensor_obligatorio',
 'Ascensor obligatorio: Decreto 293/2009 accesibilidad Andalucia',
 'Obra nueva PB+3 (4 plantas) o mas: ascensor obligatorio. Rehabilitacion >25% en edificio >=4 plantas: instalar ascensor o justificar inviabilidad tecnica/economica. Cabina minima 1.10 x 1.40 m + puerta 90 cm.',
 'Decreto 293/2009 Accesibilidad Andalucia + CTE DB-SUA',
 'https://www.juntadeandalucia.es',
 '{"project_type":["obra_nueva","rehabilitacion","cambio_uso"]}'::jsonb,
 '{"property_floors_above_ground":">=4","reform_pct_value":">=25"}'::jsonb,
 'depende',
 '["Andalucia exige puerta 90 cm (vs 80 cm CTE basico). Verificar cabina disponible.","Subvencion Junta Andalucia + estatal hasta 60% cost si comunidad acuerda."]'::jsonb,
 'critico','Decreto 293/2009'),

('sevilla','Sevilla','Sevilla','Andalucia','habitabilidad_decreto_60_2010','habitabilidad_minima',
 'Decreto 60/2010 Andalucia: condiciones habitabilidad - 25 m2 estudio',
 'Habitabilidad Andalucia: estudio minimo 25 m2 utiles (similar Madrid). 1 dormitorio >= 30 m2. Cada dormitorio adicional +9 m2 (mas que Madrid +8). Bano: ducha o banera + lavabo + wc.',
 'Decreto 60/2010 Andalucia Habitabilidad',
 'https://www.juntadeandalucia.es',
 '{"project_type":["obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"creates_dwelling":true}'::jsonb,
 'depende',
 '["Andalucia +9 m2 por dormitorio adicional (vs +8 Madrid). Mas exigente en grandes.","Cocinas integradas permitidas en estancias >20 m2."]'::jsonb,
 'critico','Decreto 60/2010 AND'),

('sevilla','Sevilla','Sevilla','Andalucia','dbhe_cte_sevilla_zona_b4','eficiencia_energetica',
 'CTE DB-HE Sevilla zona B4 - clima caluroso, refrigeracion critica',
 'Reforma >25% envolvente: DB-HE0/HE1. Sevilla zona climatica B4 (mas calurosa Espana peninsular): proteccion solar fundamental. Carpinterias U <= 1.8 W/m2K + factor solar g <= 0.35 orientacion S/O/E. Ventilacion cruzada noche obligatoria diseno.',
 'CTE DB-HE (RD 732/2019 zona B4)',
 'https://www.codigotecnico.org',
 '{"project_type":["reforma","cambio_uso","obra_nueva"]}'::jsonb,
 '{"reform_pct_envelope":">=25"}'::jsonb,
 'depende',
 '["Sevilla zona B4 extrema: persianas, toldos, vegetacion sur obligatorios diseno.","Aerotermia + solar PV recuperacion 4-5 anos en Sevilla por sol abundante."]'::jsonb,
 'critico','CTE DB-HE B4'),

('sevilla','Sevilla','Sevilla','Andalucia','ite_andalucia_decreto_2_2012','ite_iee',
 'ITE Andalucia: edificios >50 anos + Inspeccion Tecnica',
 'Decreto 2/2012 Andalucia: ITE obligatoria edificios >50 anos, renovacion 10 anos. Mas reciente que CAM/CAT, con requisitos accesibilidad + eficiencia. Sin ITE no licencia reforma >25%.',
 'Decreto 2/2012 Andalucia ITE',
 'https://www.juntadeandalucia.es',
 '{"project_type":["reforma","cambio_uso","division_horizontal"]}'::jsonb,
 '{"building_age_years":">=50"}'::jsonb,
 'depende',
 '["Andalucia umbral 50 anos (igual Valencia).","Coste ITE Sevilla 500-1000 EUR segun mida."]'::jsonb,
 'critico','Decreto 2/2012 AND'),

('sevilla','Sevilla','Sevilla','Andalucia','patio_minimo_sevilla','patios_ventilacion',
 'Patios tradicionales sevillanos + minimos PGOU',
 'PGOU Sevilla: patio ventilacion minimo 12 m2 si ventila a dormitorios (mas que Madrid 9 m2). Patios tipicos sevillanos (corral, traspatio) protegidos en Casco Antiguo. Refrescamiento pasivo natural valorado positivamente.',
 'PGOU Sevilla 2006 + Plan Especial Casco Antiguo',
 'https://www.sevilla.org',
 '{"project_type":["obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"requires_patio":true}'::jsonb,
 'depende',
 '["Casco Antiguo: patio tradicional protegido - no se puede cubrir/cerrar sin Plan Especial.","12 m2 minimo dormitorio (mas Madrid 9 m2). Verificar en cambios uso."]'::jsonb,
 'importante','PGOU Sevilla'),

('sevilla','Sevilla','Sevilla','Andalucia','aparcamiento_sevilla_centro','aparcamiento_obligatorio',
 'Aparcamiento Sevilla: 1 plaza/100 m2 + exoneracion Casco Antiguo',
 'Obra nueva o ampliacion >25% residencial: 1 plaza por 100 m2 construidos. Casco Antiguo y zonas declaradas BIC: exoneracion casi total (calles estrechas, imposibilidad tecnica). PGOU 2006 admite cuota economica sustitutiva.',
 'PGOU Sevilla 2006 + Ordenanza Aparcamiento',
 'https://www.sevilla.org',
 '{"project_type":["obra_nueva","ampliacion"]}'::jsonb,
 '{"is_residential":true,"property_area_m2":">=100"}'::jsonb,
 'depende',
 '["Casco Antiguo: cuota sustitutiva ~7000-12000 EUR por plaza no construida.","Anchura calles centro Sevilla impide rampa garaje subterraneo - exoneracion habitual."]'::jsonb,
 'importante','PGOU Sevilla'),

('sevilla','Sevilla','Sevilla','Andalucia','horario_obras_sevilla','horario_obras',
 'Horario obras Sevilla: L-V 8:00-21:00, S 9:00-15:00, D festivos prohibido',
 'Obras zona urbana solo L-V 8:00-21:00 y S 9:00-15:00. Domingos prohibido. Maquinaria pesada (martillo, vibrador) solo L-V 9:00-19:00. Semana Santa + Feria: restricciones adicionales en zonas afectadas.',
 'Ordenanza Acustica Sevilla',
 'https://www.sevilla.org',
 '{"project_type":["any"]}'::jsonb,
 '{"any":true}'::jsonb,
 'sin_licencia',
 '["Semana Santa (zona ruta procesiones) obras suspendidas. Planifica calendario.","Feria de Abril (parking Real): obras zona Los Remedios + ZAS suspendidas."]'::jsonb,
 'importante','Ordenanza Sevilla'),

('sevilla','Sevilla','Sevilla','Andalucia','rcd_sevilla_lipasam','gestion_rcd',
 'RCD Sevilla: gestion Lipasam + Decreto 73/2012 Andalucia',
 'Residuos Construccion Demolicion: separacion origen + entrega gestor autorizado. Lipasam (servicio limpieza Sevilla) gestiona puntos verdes municipales. Fianza ~1.5% PEM. Certificado gestor obligatorio devolucion.',
 'Decreto 73/2012 RCD Andalucia + RD 105/2008',
 'https://www.lipasam.es',
 '{"project_type":["reforma","obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"generates_rcd":true,"estimated_rcd_m3":">=5"}'::jsonb,
 'sin_licencia',
 '["Lipasam puntos verdes admiten <2 m3 sin gestor.","Fianza recuperable solo con certificado gestor RERA."]'::jsonb,
 'importante','Decreto 73/2012 AND'),

('sevilla','Sevilla','Sevilla','Andalucia','andamio_via_publica_sevilla','tasas_andamios_vados',
 'Andamio Sevilla: tasa Movilidad + zona ZAS restricciones',
 'Andamio, contenedor o vado en acera/calzada: autorizacion Servicio Movilidad + tasa diaria ~0.4-0.8 EUR/m2/dia. Zonas ZAS (Casco Antiguo, calles peatonales) restricciones horarias adicionales. Andamios >6m con certificado tecnico.',
 'Ordenanza Mobiliario Urbano + Tasas Sevilla',
 'https://www.sevilla.org',
 '{"project_type":["reforma","obra_nueva"]}'::jsonb,
 '{"requires_public_space":true}'::jsonb,
 'sin_licencia',
 '["Casco Antiguo Sevilla: suministros materiales solo madrugada (6:00-9:00) por restricciones trafico.","Procesiones Semana Santa zona afectada: desmontar andamios temporalmente."]'::jsonb,
 'recomendable','Ordenanza Sevilla'),

('sevilla','Sevilla','Sevilla','Andalucia','contador_agua_emasesa','instalaciones_servicios',
 'Contador agua individual EMASESA Sevilla',
 'Reformas integrales o division horizontal: contador individual obligatorio EMASESA (concesionaria Sevilla). Sin contador no hay alta servicio. Acometida ajustada cabal/potencia.',
 'Reglamento EMASESA + Decreto 60/2010 AND',
 'https://www.emasesa.com',
 '{"project_type":["reforma","division_horizontal","obra_nueva"]}'::jsonb,
 '{"is_residential":true,"reform_pct_value":">=25"}'::jsonb,
 'sin_licencia',
 '["EMASESA tramite 4-6 semanas para nueva acometida.","Edificios pre-1985 contador comun: subvencion JA para individualizar."]'::jsonb,
 'importante','EMASESA'),

('sevilla','Sevilla','Sevilla','Andalucia','renovables_solar_sevilla','eficiencia_energetica',
 'Solar termica + PV obligatorias - Sevilla maxima radiacion peninsular',
 'Reforma integral residencial o obra nueva: solar termica ACS obligatoria CTE DB-HE4. Sevilla zona radiacion V (maxima Espana): solar PV recomendada por amortizacion <5 anos. Caldera gasoil prohibida sustituir - obligatorio aerotermia, biomasa o gas condensacion.',
 'CTE DB-HE4 + RD 178/2021 + PNIEC',
 'https://www.codigotecnico.org',
 '{"project_type":["reforma","cambio_uso","obra_nueva"]}'::jsonb,
 '{"replaces_heating":true}'::jsonb,
 'sin_licencia',
 '["Sevilla zona V radiacion: PV autoconsumo amortizacion 4-5 anos. Inversion segura.","Junta Andalucia + IDAE subvenciones aerotermia hasta 40% cost."]'::jsonb,
 'importante','CTE DB-HE4 + PNIEC'),

('sevilla','Sevilla','Sevilla','Andalucia','amianto_sevilla_pre1980','otros',
 'Amianto pre-1980 Sevilla: RERA + Plan Trabajo Inspeccion JA',
 'Reformas con demolicion en edificios pre-1980: evaluacion amianto obligatoria. Si confirmado: empresa RERA Andalucia + Plan Trabajo aprobado por Inspeccion Trabajo JA. Plazo aprobacion 3-4 semanas.',
 'RD 396/2006 + Ley 31/1995 PRL',
 'https://www.boe.es/buscar/act.php?id=BOE-A-2006-6474',
 '{"project_type":["reforma","obra_nueva"]}'::jsonb,
 '{"building_age_years":">=45","demolition_works":true}'::jsonb,
 'sin_licencia',
 '["Edificios Sevilla 1950-1975: bajantes uralita comunes. Verificar antes demolicion.","Cost retirada RERA 35-65 EUR/ml. Inversion obligatoria en presupuesto."]'::jsonb,
 'critico','RD 396/2006'),

('sevilla','Sevilla','Sevilla','Andalucia','altura_libre_sevilla_25','habitabilidad_minima',
 'Altura libre minima Sevilla: 2.50 m piezas habitables, 2.20 m banos',
 'Decreto 60/2010 Andalucia: altura libre 2.50 m piezas habitables (estar, dormitorios, cocina). 2.20 m banos, pasillos, distribuidores. Descuelgues max 25% superficie.',
 'Decreto 60/2010 Andalucia',
 'https://www.juntadeandalucia.es',
 '{"project_type":["obra_nueva","cambio_uso","reforma"]}'::jsonb,
 '{"affects_ceiling_height":true}'::jsonb,
 'depende',
 '["Sevilla 2.20 m banos (igual Madrid/Valencia, menos exigente que BCN 2.40).","Casco Antiguo edificios antiguos: techos bajos frecuentes - cambio uso problematico."]'::jsonb,
 'importante','Decreto 60/2010 AND'),

('sevilla','Sevilla','Sevilla','Andalucia','cambio_uso_sevilla_centro','compatibilidad_uso',
 'Cambio uso terciario->residencial Sevilla + Casco Antiguo restricciones',
 'Convertir local/oficina en vivienda: (1) compatibilidad uso en zona PGOU, (2) Decreto 60/2010 habitabilidad, (3) altura libre 2.50 m, (4) ventilacion natural calle o patio, (5) ITE vigente, (6) Casco Antiguo: informe Patrimonio JA + restriccion cambios fachada.',
 'PGOU Sevilla 2006 + LOUA + Plan Especial Casco Antiguo',
 'https://www.sevilla.org',
 '{"project_type":["cambio_uso"]}'::jsonb,
 '{"new_use":"residencial","origin_use":["terciario","comercial","oficina"]}'::jsonb,
 'licencia_obra_mayor',
 '["Casco Antiguo Sevilla: cambio uso restringido para preservar mix comercial historico.","Locales con techos <2.50 m en centro: imposible conversion sin altura sotano."]'::jsonb,
 'critico','PGOU + LOUA + Plan Especial')

ON CONFLICT (municipio_slug, rule_key) DO UPDATE SET
  rule_description = EXCLUDED.rule_description,
  normative_reference = EXCLUDED.normative_reference,
  normative_url = EXCLUDED.normative_url,
  applies_to = EXCLUDED.applies_to,
  triggers = EXCLUDED.triggers,
  license_implication = EXCLUDED.license_implication,
  pitfalls = EXCLUDED.pitfalls,
  severity = EXCLUDED.severity,
  version_rule = municipal_pgou_rules.version_rule + 1,
  last_verified_at = now(),
  updated_at = now();

INSERT INTO applied_migrations (filename, notes) VALUES
  ('080_municipal_pgou_sevilla.sql', 'E.2 plan Opus: seed Sevilla (18 reglas PGOU 2006 + LOUA + Casco Antiguo BIC UNESCO + clima B4)')
ON CONFLICT (filename) DO NOTHING;

COMMIT;

-- rollback: DELETE FROM municipal_pgou_rules WHERE municipio_slug = 'sevilla'; DELETE FROM applied_migrations WHERE filename = '080_municipal_pgou_sevilla.sql';
