-- 081: Fase E.2 - SEED Bilbao (PGOU 1995 + Ley 2/2006 Suelo Vasco + Casco Viejo BIC + pendientes)
-- 18 reglas.

BEGIN;

INSERT INTO municipal_pgou_rules (municipio_slug, municipio_nombre, provincia, ccaa, rule_key, rule_category, rule_title, rule_description, normative_reference, normative_url, applies_to, triggers, license_implication, pitfalls, severity, source_doc) VALUES

('bilbao','Bilbao','Bizkaia','Pais Vasco','reforma_simple_comunicacion_bilbao','tramite_licencia',
 'Reforma interior simple Bilbao: comunicacion previa',
 'Reformas que no afectan estructura, fachada ni instalaciones comunes (pintura, pavimentos, sanitarios, ventanas sin modificar hueco): comunicacion previa. Memoria firmada + fotos. Inicio inmediato si Comunicacion I; Comunicacion II 15 dias.',
 'Ordenanza Bilbao + Ley 2/2006 Suelo Vasco',
 'https://www.bilbao.eus/cs/Satellite?c=Page&cid=3000005010&pagename=Bilbaonet/Page/BIO_Contenedor',
 '{"project_type":["reforma","actuacion_simple"]}'::jsonb,
 '{"affects_structure":false,"changes_layout":false}'::jsonb,
 'comunicacion_previa',
 '["Bilbao distingue Comunicacion I (inicio inmediato) y II (espera 15 dias).","Casco Viejo: incluso Comunicacion I lleva control adicional - documentar exhaustivo."]'::jsonb,
 'critico','Ordenanza Bilbao'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','reforma_distribucion_licencia_bilbao','tramite_licencia',
 'Reforma cambio distribucion: licencia obras menores',
 'Modificar tabiqueria interior sin elementos estructurales: licencia obras menores. Proyecto tecnico firmado COAVN (Colegio Arquitectos Vasco-Navarro) o COAATIB (Aparejadores Bizkaia). Plazo resolucion 1-2 mesos.',
 'Ley 2/2006 Suelo Vasco + PGOU Bilbao 1995',
 'https://www.bilbao.eus',
 '{"project_type":["reforma"]}'::jsonb,
 '{"changes_layout":true,"affects_structure":false}'::jsonb,
 'licencia_obra_menor',
 '["Visado COAVN obligatorio en cambio distribucion. Coste ~250-450 EUR.","Bilbao mas estricto que Madrid en obras menores - exige plano antes-despues."]'::jsonb,
 'critico','Ley 2/2006'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','obra_mayor_bilbao','tramite_licencia',
 'Obra mayor Bilbao: estructura, cambio uso, division horizontal',
 'Afectar elementos estructurales, modificar fachada, cambio de uso, division horizontal: licencia obra mayor. Proyecto basico + ejecucion visado COAVN. Plazo 3-5 mesos. ICIO Bilbao 5% PEM (mas alto Espana).',
 'Ley 2/2006 art. 207 + PGOU Bilbao 1995',
 'https://www.bilbao.eus',
 '{"project_type":["reforma","cambio_uso","division_horizontal","obra_nueva","ampliacion"]}'::jsonb,
 '{"affects_structure":true}'::jsonb,
 'licencia_obra_mayor',
 '["Bilbao ICIO 5% PEM (vs 4% Madrid, 3.3% Valencia). Pais Vasco mas caro fiscalmente.","Plazo obra mayor 3-5 mesos. Planifica con margen."]'::jsonb,
 'critico','Ley 2/2006'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','casco_viejo_bic_bilbao','proteccion_patrimonio',
 'Casco Viejo Bilbao declarado BIC + Las Siete Calles protegidas',
 'Casco Viejo Bilbao (Las Siete Calles + Plaza Nueva + Mercado Ribera) declarado BIC. Cualquier intervencion fachada, cubierta o elementos catalogados requiere informe Departamento Cultura Gobierno Vasco + autorizacion Diputacion Foral Bizkaia. Materiales tradicionales: piedra arenisca, madera, hierro forjado, teja arabe.',
 'Ley 7/1990 Patrimonio Cultural Vasco + Plan Especial Casco Viejo',
 'https://www.kultura.ejgv.euskadi.eus',
 '{"property_type":["any"]}'::jsonb,
 '{"location_zone":["casco_viejo","siete_calles","plaza_nueva","ribera","bic"],"affects_facade":true}'::jsonb,
 'licencia_obra_mayor',
 '["Casco Viejo: doble informe Gobierno Vasco + Diputacion (+2-3 mesos plazo).","Materiales tradicionales obligatorios. Sustitucion ventanas: solo madera o hierro forjado."]'::jsonb,
 'critico','Plan Especial Casco Viejo'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','ascensor_obligatorio_euskadi','ascensor_obligatorio',
 'Ascensor obligatorio Pais Vasco: Decreto 68/2000 + LANE Etxebizitza',
 'Obra nueva PB+3 (4 plantas) o mas: ascensor obligatorio. Rehabilitacion: si edificio >=PB+3 y reforma >25% valor, instalar ascensor o justificar inviabilidad. Cabina minima 1.10 x 1.40 m + puerta 90 cm. LANE (Ley 3/2015 Vivienda Vasca) subvenciones reforzadas.',
 'Decreto 68/2000 Accesibilidad Euskadi + Ley 3/2015 LANE',
 'https://www.euskadi.eus',
 '{"project_type":["obra_nueva","rehabilitacion","cambio_uso"]}'::jsonb,
 '{"property_floors_above_ground":">=4","reform_pct_value":">=25"}'::jsonb,
 'depende',
 '["Pais Vasco subvenciones ascensor mas altas Espana (hasta 70% cost si LANE).","Bilbao pendientes pronunciadas (Begona, Solokoetxe): incluso PB+2 muchas veces requiere ascensor por accesibilidad calle."]'::jsonb,
 'critico','Decreto 68/2000'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','habitabilidad_decreto_317_2002','habitabilidad_minima',
 'Decreto 317/2002 Euskadi: condiciones habitabilidad - 35 m2 estudio',
 'Habitabilidad Euskadi: estudio minimo 35 m2 utiles (mas exigente que Madrid 25, similar a BCN 36). Cada dormitorio >= 8 m2. Bano completo (ducha+lavabo+wc) + cocina separada o integrada en estancia >18 m2. Plaza trastero recomendada >=5 m2.',
 'Decreto 317/2002 Euskadi Habitabilidad',
 'https://www.euskadi.eus',
 '{"project_type":["obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"creates_dwelling":true}'::jsonb,
 'depende',
 '["Euskadi 35 m2 estudio (entre Madrid 25 y BCN 36).","Trastero recomendado >=5 m2 - no obligatorio pero valorado en cedula."]'::jsonb,
 'critico','Decreto 317/2002'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','dbhe_cte_bilbao_zona_c1','eficiencia_energetica',
 'CTE DB-HE Bilbao zona C1 - clima atlantico, humedad + frio invierno',
 'Reforma >25% envolvente: DB-HE0/HE1. Bilbao zona C1 atlantica (humedad alta + frio invierno moderado): aislamiento envolvente prioridad. Carpinterias U <= 1.6 W/m2K (mas exigente que zona B). Ventilacion mecanica controlada recomendada para evitar condensaciones.',
 'CTE DB-HE (RD 732/2019 zona C1)',
 'https://www.codigotecnico.org',
 '{"project_type":["reforma","cambio_uso","obra_nueva"]}'::jsonb,
 '{"reform_pct_envelope":">=25"}'::jsonb,
 'depende',
 '["Bilbao zona C1: aislamiento +30% mas exigente que zona B (Madrid, Sevilla).","Humedad alta: ventilacion mecanica + aislamiento sin puentes termicos clave."]'::jsonb,
 'critico','CTE DB-HE C1'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','ite_euskadi_50anys','ite_iee',
 'ITE Euskadi: edificios >50 anos cada 10 anos',
 'Inspeccion Tecnica Construccion (ITC) Euskadi: edificios >50 anos. Renovacion 10 anos. Sin ITE vigente no licencia reforma >25%. Coste ITC Bilbao 600-1100 EUR.',
 'Decreto 241/2012 ITE Euskadi',
 'https://www.euskadi.eus',
 '{"project_type":["reforma","cambio_uso","division_horizontal"]}'::jsonb,
 '{"building_age_years":">=50"}'::jsonb,
 'depende',
 '["Euskadi llama ITC (Inspeccion Tecnica Construccion) vs ITE en otros - mismo concepto.","Casco Viejo Bilbao edificios pre-1900: ITC obligatoria con renovacion 5 anos en algunos."]'::jsonb,
 'critico','Decreto 241/2012'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','patio_bilbao_4x4','patios_ventilacion',
 'Patio ventilacion Bilbao: minimo 4x4 m + galerias acristaladas',
 'PGOU Bilbao: patio ventilacion minimo 4x4 m (16 m2) si ventila piezas habitables. Patios mas pequenos (3x3) solo banos/cuinas. Galerias acristaladas tipicas Bilbao: protegidas en Ensanche - no se pueden cerrar sin Plan Especial.',
 'PGOU Bilbao 1995',
 'https://www.bilbao.eus',
 '{"project_type":["obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"requires_patio":true}'::jsonb,
 'depende',
 '["Bilbao 16 m2 minimo (igual BCN, mas Madrid 9).","Galerias acristaladas Indautxu/Ensanche: catalogadas - intocables sin Plan Especial."]'::jsonb,
 'critico','PGOU Bilbao 1995'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','aparcamiento_bilbao_centro','aparcamiento_obligatorio',
 'Aparcamiento Bilbao: 1 plaza/100 m2 + exoneracion Casco Viejo/Indautxu',
 'Obra nueva residencial: 1 plaza por 100 m2 construidos. Casco Viejo: exoneracion total (calles peatonales). Indautxu/Abando edificios protegidos: exoneracion parcial o cuota sustitutiva.',
 'PGOU Bilbao + Ordenanza Aparcamiento',
 'https://www.bilbao.eus',
 '{"project_type":["obra_nueva","ampliacion"]}'::jsonb,
 '{"is_residential":true,"property_area_m2":">=100"}'::jsonb,
 'depende',
 '["Casco Viejo Bilbao 100% peatonal: imposible aparcamiento - exoneracion automatica.","Cuota sustitutiva Bilbao ~9000-13000 EUR por plaza no construida."]'::jsonb,
 'importante','PGOU Bilbao'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','horario_obras_bilbao','horario_obras',
 'Horario obras Bilbao: L-V 8:00-20:00, S 9:00-13:00, D festivos prohibido',
 'Obras zona urbana solo L-V 8:00-20:00 (igual Madrid/BCN) y S 9:00-13:00 (mas corto que otras ciudades). Domingos prohibido. Maquinaria pesada solo L-V 9:00-19:00. Asteasuna festivos locales (Aste Nagusia, Semana Grande) restricciones zona.',
 'Ordenanza Acustica Bilbao',
 'https://www.bilbao.eus',
 '{"project_type":["any"]}'::jsonb,
 '{"any":true}'::jsonb,
 'sin_licencia',
 '["Bilbao S 9:00-13:00 mas corto que otras ciudades. Planificar.","Aste Nagusia (Semana Grande, agosto): obras suspendidas zona Casco Viejo + Abando."]'::jsonb,
 'importante','Ordenanza Bilbao'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','rcd_bilbao_zabor','gestion_rcd',
 'RCD Bilbao: gestion Zabor + Decreto 112/2012 Euskadi',
 'Residuos Construccion Demolicion: separacion origen + entrega gestor autorizado registro Euskadi. Zabor (servicio Bilbao) gestiona puntos verdes municipales. Fianza ~1-2% PEM. Certificado gestor obligatorio devolucion fianza.',
 'Decreto 112/2012 RCD Euskadi + RD 105/2008',
 'https://www.euskadi.eus',
 '{"project_type":["reforma","obra_nueva","cambio_uso","division_horizontal"]}'::jsonb,
 '{"generates_rcd":true,"estimated_rcd_m3":">=5"}'::jsonb,
 'sin_licencia',
 '["Zabor puntos verdes admiten <2 m3 residenciales sin gestor.","Fianza recuperable solo con certificado gestor registrado Euskadi."]'::jsonb,
 'importante','Decreto 112/2012'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','andamio_bilbao_pendientes','tasas_andamios_vados',
 'Andamio Bilbao: tasa Movilidad + pendientes pronunciadas',
 'Andamio, contenedor o vado: autorizacion Movilidad + tasa ~0.4-0.7 EUR/m2/dia. Calles con pendiente >12% (frecuentes en Bilbao): certificado tecnico extra de estabilidad. Andamios >6m con calculo estructural + seguro RC.',
 'Ordenanza Mobiliario Urbano Bilbao',
 'https://www.bilbao.eus',
 '{"project_type":["reforma","obra_nueva"]}'::jsonb,
 '{"requires_public_space":true}'::jsonb,
 'sin_licencia',
 '["Pendientes Bilbao (>12%): andamio sobre rampa requiere calculo especifico.","Casco Viejo peatonal: suministro materiales solo madrugada (6:00-9:00)."]'::jsonb,
 'recomendable','Ordenanza Bilbao'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','contador_agua_consorcio','instalaciones_servicios',
 'Contador agua individual Consorcio Aguas Bilbao Bizkaia',
 'Reformas integrales o division horizontal: contador individual Consorcio Aguas Bilbao Bizkaia. Sin contador no hay alta servicio. Acometida ajustada cabal/potencia. Tramite Consorcio 4-6 semanas.',
 'Reglamento Consorcio Aguas + Decreto 317/2002',
 'https://www.consorciodeaguas.eus',
 '{"project_type":["reforma","division_horizontal","obra_nueva"]}'::jsonb,
 '{"is_residential":true,"reform_pct_value":">=25"}'::jsonb,
 'sin_licencia',
 '["Consorcio Aguas Bilbao Bizkaia gestiona tambien municipios alrededor - mismo proceso.","Edificios pre-1990 contador comun: subvencion Gobierno Vasco para individualizar."]'::jsonb,
 'importante','Consorcio Aguas'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','renovables_euskadi_pne','eficiencia_energetica',
 'Renovables obligatorias Euskadi: Decreto 178/2015 + PNIEC',
 'Reforma integral residencial: sustitucion caldera gasoil prohibida (RD 178/2021). Obligatorio aerotermia, biomasa pellet, geotermia o gas natural condensacion. Pais Vasco subvenciones EVE (Ente Vasco Energia) entre las mas altas Espana - hasta 50% cost en aerotermia.',
 'Decreto 178/2015 Euskadi + RD 178/2021',
 'https://www.eve.eus',
 '{"project_type":["reforma","cambio_uso","obra_nueva"]}'::jsonb,
 '{"replaces_heating":true}'::jsonb,
 'sin_licencia',
 '["EVE subvenciones hasta 50% (mas altas Espana). Aprovechar.","Geotermia tiene sentido tecnico en Bilbao por estabilidad temperatura subterraneo."]'::jsonb,
 'importante','Decreto 178/2015 Euskadi'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','amianto_pre1980_bilbao','otros',
 'Amianto pre-1980 Bilbao: RERA + Plan Trabajo Osalan',
 'Reformas con demolicion en edificios pre-1980 Bilbao: evaluacion amianto obligatoria. Si confirmado: empresa RERA Euskadi + Plan Trabajo aprobado por Osalan (Instituto Salud Laboral Vasco). Plazo aprobacion 3-4 semanas.',
 'RD 396/2006 + Decreto 110/2008 Osalan',
 'https://www.osalan.euskadi.eus',
 '{"project_type":["reforma","obra_nueva"]}'::jsonb,
 '{"building_age_years":">=45","demolition_works":true}'::jsonb,
 'sin_licencia',
 '["Edificios industriales/portuarios Bilbao pre-1980: alto riesgo amianto en cubiertas.","Osalan revision mas estricta que Inspeccion Trabajo en otras CCAA - planifica plazo."]'::jsonb,
 'critico','Decreto 110/2008 Osalan'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','altura_libre_bilbao_25','habitabilidad_minima',
 'Altura libre minima Bilbao: 2.50 m piezas habitables, 2.30 m banos',
 'Decreto 317/2002 Euskadi: altura libre 2.50 m piezas habitables. 2.30 m banos, cuinas pequenas, pasillos (mas exigente que Madrid 2.20 m). Descuelgues max 25% superficie.',
 'Decreto 317/2002 Euskadi',
 'https://www.euskadi.eus',
 '{"project_type":["obra_nueva","cambio_uso","reforma"]}'::jsonb,
 '{"affects_ceiling_height":true}'::jsonb,
 'depende',
 '["Bilbao 2.30 m banos (vs 2.20 Madrid). Mas exigente.","Edificios pre-1950 Casco Viejo: techos 2.20-2.40 m - imposible cambio uso sin estructura nueva."]'::jsonb,
 'importante','Decreto 317/2002'),

('bilbao','Bilbao','Bizkaia','Pais Vasco','cambio_uso_bilbao_pne','compatibilidad_uso',
 'Cambio uso terciario->residencial Bilbao + LANE etxebizitza',
 'Convertir local/oficina en vivienda Bilbao: (1) compatibilidad uso PGOU, (2) Decreto 317/2002 habitabilidad (35 m2 minimo, 2.50 m altura), (3) ventilacion natural calle o patio 16 m2, (4) ITC vigente, (5) Casco Viejo: informe Patrimonio Gobierno Vasco + Diputacion. Pais Vasco prioriza conversion en Plan Vivienda.',
 'PGOU Bilbao + Decreto 317/2002 + Ley 3/2015 LANE',
 'https://www.bilbao.eus',
 '{"project_type":["cambio_uso"]}'::jsonb,
 '{"new_use":"residencial","origin_use":["terciario","comercial","oficina"]}'::jsonb,
 'licencia_obra_mayor',
 '["LANE Pais Vasco prioriza conversion oficinas->vivienda: subvenciones reforzadas.","Casco Viejo Bilbao: patio 16 m2 dificilmente disponible en bajos. Conversion limitada."]'::jsonb,
 'critico','Ley 3/2015 LANE')

ON CONFLICT (municipio_slug, rule_key) DO UPDATE SET
  rule_description = EXCLUDED.rule_description,
  normative_reference = EXCLUDED.normative_reference,
  normative_url = EXCLUDED.normative_url,
  applies_to = EXCLUDED.applies_to,
  triggers = EXCLUDED.triggers,
  license_implication = EXCLUDED.license_implication,
  pitfalls = EXCLUDED.pitfalls,
  severity = EXCLUDED.severity,
  version_rule = municipal_pgou_rules.version_rule + 1,
  last_verified_at = now(),
  updated_at = now();

INSERT INTO applied_migrations (filename, notes) VALUES
  ('081_municipal_pgou_bilbao.sql', 'E.2 plan Opus: seed Bilbao (18 reglas PGOU 1995 + Ley 2/2006 Suelo Vasco + Casco Viejo BIC + clima C1 atlantico)')
ON CONFLICT (filename) DO NOTHING;

COMMIT;

-- rollback: DELETE FROM municipal_pgou_rules WHERE municipio_slug = 'bilbao'; DELETE FROM applied_migrations WHERE filename = '081_municipal_pgou_bilbao.sql';
